name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: app

    - name: Build TypeScript
      run: npm run build
      working-directory: app

    - name: Run tests
      run: npm test
      working-directory: app
    
    - name: Build Docker image
      run: |
        docker build -t hamzao119/devops-assistant:1.0 ./app
        docker tag hamzao119/devops-assistant:1.0 hamzao119/devops-assistant:latest


    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      

    - name: Push Docker image
      run: |
        docker push hamzao119/devops-assistant:1.0
        docker push hamzao119/devops-assistant:latest
